# This workflow will push and update articles on dev.to each time a new
# commit is pushed to the main branch.
#
# To make it work, you need a dev.to API key, see:
# https://docs.dev.to/api/#section/Authentication/api_key
#
# Once you have generated the token, you need to add them as a secret in your
# GitHub repository:
# - DEVTO_TOKEN: your dev.to API key
# See https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets
# for more information about GitHub secrets.

name: publish
on:
  push:
    branches: [BRANCH]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      with:
        # The dev.to API key.
        # See https://docs.dev.to/api/#section/Authentication/api_key
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        # The GitHub personal access token, used to create commits for updated files.
        # If you have a protected branch, you need to create a commit with the
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # (Optional) The GitHub repository to use for image hosting.
        # If not specified, the current repository will be used.
        repository: USERNAME/REPO
        # (Optional) The GitHub branch to use for image hosting.
        # If not specified, the current branch will be used.
        branch: BRANCH
        # (Optional) The files to publish. Default is "posts/**/*.md"
        files_glob: 'posts/**/*.md'
        # (Optional) Use conventional commit messages. Default is false.
        # See https://www.conventionalcommits.org. 
        conventional_commits: true
